### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by johnyqi** [tw2113/custom-post-type-ui-capabilities#2]
Hi, I was wondering if there is a way to generate JSON link from custom posts? I tried with one plugin, to add feed/json, but it didn't work. Any ideas?

thank you (btw, awesome plugin)

**Comment by tw2113** [comment]
You should be able to get a JSON representation of posts using the WordPress REST API that comes with WordPress core these days.

https://developer.wordpress.org/rest-api/

Closing as not an actual issue on the plugin, but just a question. We can still discuss even with the issue closed.

**Comment by johnyqi** [comment]
Hi, thank you, I already got that link, it’s all good, works perfectly :-)
